lang: Fix system realtime message type codes
supercollider/supercollider pull request #5201
Opened 2020-10-18 01:51 UTC by jamshark70

## Purpose and Motivation

Fixes #5198 (for Linux, not totally sure about Windows -- there is a pending PR to fix a related crash in Windows).

In Linux, song position pointer and song select messages were sent with an incorrect sysrt message type code. We thought we were getting the type code from `evt->data.control.channel` (and maybe that was actually the case a decade or two ago), but I found in testing that this is always 0.

SC_CoreMIDI.cpp and SC_PortMIDI.cpp simply pass the code byte as a constant. So, I'm updating SC_AlsaMIDI.cpp accordingly.

I also found that the song position data value (`(pkt->data[2] << 7) | pkt->data[1]` for Core MIDI) is a wrong calculation in Alsa. Through debugging posts, I found that `evt->data.control.value` is already the 14-bit value, and doing `evt->data.control.value << 7` means that the value passed into the language is 128 times the correct value. With this change, if I send MIDI bytes `242 101 2`, the expected song position is `101 | (2 << 7)` == 357, and 357 is in fact the value received in the language.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

2022-02-20 21:01 UTC, joshpar requested changes
@jamshark70 - can you think of any test cases we can include with this PR?

2022-02-21 00:59 UTC, jamshark70 commented
> can you think of any test cases we can include with this PR?

In Linux, it's possible to connect SC MIDI to itself.

```
MIDIClient.init(1, 1);
m = MIDIOut(0).connect(MIDIClient.destinations.detectIndex { |target| target.device == "SuperCollider" });
```

Then `m.songPtr(...)` and `m.songSelect(...)` will go through the MIDI backend.

In Windows, I think you need a separate loopback utility (e.g. [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html)) -- I'm pretty sure we don't want to ship third-party utilities, only for the purpose of unit testing.

However, Windows doesn't have the incorrect status byte bug (by reading source code). I have no way to verify if Windows does or does not have the incorrect song pointer bug.

2022-08-15 14:57 UTC, joshpar commented
Hi all - we'd like to pull this in for 3.13.0 and are planning an RC for that after our meeting on Aug, 27, 2022. Anything else to add? Or can we close this?

2022-08-16 00:51 UTC, jamshark70 commented
I need to close it and resubmit.

2022-08-16 00:51 UTC, closed without merging