cmake: improve FindPortaudio.cmake
supercollider/supercollider pull request #5206
Opened 2020-10-20 03:26 UTC by brianlheim

## Purpose and Motivation

fixes #5176, both the spurious warning message about PkgConfig and the macos/cmake compatibility issue

these are minimal changes to fix compilation on macOS; can definitely be improved further.

while i was at it i removed a bit of cruft in the module -- this business with PORTAUDIO2 wasn't really necessary and
just served to obfuscate.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested - tested locally, able to reproduce the issue before, not after this commit
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

2020-10-20 06:27 UTC, dyfer requested changes
thanks @brianlheim 
Unfortunately on macOS with CMake 3.18.4 linking still does not work. I'm getting:
```
Ld build/server/supernova/RelWithDebInfo/supernova normal x86_64
    cd /Volumes/data/Dokumenty/src/supercollider
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Volumes/data/Dokumenty/src/supercollider/build/server/supernova/RelWithDebInfo -F/Volumes/data/Dokumenty/src/supercollider/build/server/supernova/RelWithDebInfo -filelist /Volumes/data/Dokumenty/src/supercollider/build/server/supernova/SuperCollider.build/RelWithDebInfo/supernova.build/Objects-normal/x86_64/supernova.LinkFileList -mmacosx-version-min=10.13 -Xlinker -object_path_lto -Xlinker /Volumes/data/Dokumenty/src/supercollider/build/server/supernova/SuperCollider.build/RelWithDebInfo/supernova.build/Objects-normal/x86_64/supernova_lto.o -stdlib=libc++ -Wl,-search_paths_first -Wl,-headerpad_max_install_names -stdlib=libc++ /Volumes/data/Dokumenty/src/supercollider/build/server/supernova/RelWithDebInfo/libsupernova.a /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/liboscpack.a /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/libtlsf.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/libboost_thread_lib.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd -lportaudio /usr/local/opt/libsndfile/lib/libsndfile.dylib /usr/local/lib/libfftw3f.dylib /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/libboost_system_lib.a /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/libboost_filesystem_lib.a /Volumes/data/Dokumenty/src/supercollider/build/external_libraries/RelWithDebInfo/libboost_program_options_lib.a -framework Accelerate -framework CoreAudio -framework CoreServices -framework Foundation -framework ApplicationServices -framework AppKit -Xlinker -dependency_info -Xlinker /Volumes/data/Dokumenty/src/supercollider/build/server/supernova/SuperCollider.build/RelWithDebInfo/supernova.build/Objects-normal/x86_64/supernova_dependency_info.dat -o /Volumes/data/Dokumenty/src/supercollider/build/server/supernova/RelWithDebInfo/supernova
ld: library not found for -lportaudio
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```
(PortAudio installed with homebrew)

2020-10-20 13:51 UTC, brianlheim commented
@dyfer are you building from a clean directory? these variables are cached.

2020-10-20 14:00 UTC, brianlheim commented
here is how i test and the output i get:

<details>

```
cmake .. -DSUPERNOVA=1 -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) -GNinja -DCMAKE_BUILD_TYPE=Debug
ninja supernova -nv
```

[1756/1756] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -msse -msse2 -stdlib=libc++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -stdlib=libc++  server/supernova/CMakeFiles/supernova.dir/server/main.cpp.o -o server/supernova/supernova  server/supernova/libsupernova.a  external_libraries/liboscpack.a  external_libraries/libtlsf.a  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libpthread.tbd  external_libraries/libboost_thread_lib.a  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd  **/usr/local/Cellar/portaudio/19.6.0/lib/libportaudio.dylib  -framework CoreAudio  -framework AudioToolbox  -framework AudioUnit  -framework Carbon**  /usr/local/opt/libsndfile/lib/libsndfile.dylib  external_libraries/libboost_system_lib.a  external_libraries/libboost_filesystem_lib.a  external_libraries/libboost_program_options_lib.a  -framework Accelerate -framework CoreAudio -framework CoreServices  -framework Foundation -framework ApplicationServices -framework AppKit && cd /Users/brianheim/git/sc2/build/server/supernova && /usr/local/Cellar/cmake/3.18.4/bin/cmake -E make_directory /Users/brianheim/git/sc2/build/editors/sc-ide/SuperCollider.app/Contents/MacOS/../Resources/ && /usr/local/Cellar/cmake/3.18.4/bin/cmake -E copy_if_different /Users/brianheim/git/sc2/build/server/supernova/supernova /Users/brianheim/git/sc2/build/editors/sc-ide/SuperCollider.app/Contents/MacOS/../Resources

```
cmake .. -DSUPERNOVA=1 -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) -GXcode -DCMAKE_BUILD_TYPE=Debug
cmake --build . --config Debug --target supernova -- -dry-run
```

Ld build/server/supernova/Debug/supernova normal x86_64
    cd /Users/brianheim/git/sc2
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/brianheim/git/sc2/build/server/supernova/Debug -F/Users/brianheim/git/sc2/build/server/supernova/Debug -filelist /Users/brianheim/git/sc2/build/server/supernova/SuperCollider.build/Debug/supernova.build/Objects-normal/x86_64/supernova.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/brianheim/git/sc2/build/server/supernova/SuperCollider.build/Debug/supernova.build/Objects-normal/x86_64/supernova_lto.o -Xlinker -no_deduplicate -stdlib=libc++ -Wl,-search_paths_first -Wl,-headerpad_max_install_names -stdlib=libc++ /Users/brianheim/git/sc2/build/server/supernova/Debug/libsupernova.a /Users/brianheim/git/sc2/build/external_libraries/Debug/liboscpack.a /Users/brianheim/git/sc2/build/external_libraries/Debug/libtlsf.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libpthread.tbd /Users/brianheim/git/sc2/build/external_libraries/Debug/libboost_thread_lib.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd **/usr/local/Cellar/portaudio/19.6.0/lib/libportaudio.dylib -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework Carbon** /usr/local/opt/libsndfile/lib/libsndfile.dylib /Users/brianheim/git/sc2/build/external_libraries/Debug/libboost_system_lib.a /Users/brianheim/git/sc2/build/external_libraries/Debug/libboost_filesystem_lib.a /Users/brianheim/git/sc2/build/external_libraries/Debug/libboost_program_options_lib.a -framework Accelerate -framework CoreAudio -framework CoreServices -framework Foundation -framework ApplicationServices -framework AppKit -Xlinker -dependency_info -Xlinker /Users/brianheim/git/sc2/build/server/supernova/SuperCollider.build/Debug/supernova.build/Objects-normal/x86_64/supernova_dependency_info.dat -o /Users/brianheim/git/sc2/build/server/supernova/Debug/supernova

</details>

2020-10-20 17:21 UTC, dyfer commented
> @dyfer are you building from a clean directory?

Sorry! I thought I did, but apparently not. I've run it again and it indeed works fine now.

2020-10-20 17:21 UTC, dyfer approved these changes
Thanks!

2020-10-20 17:29 UTC, merged

2021-05-24 01:59 UTC, dyfer commented
For some reason I am sometimes still getting the error with CMake 3.19:
`
ld: library not found for -lportaudio
`

For me setting library path pointing to homebrew-installed libraries fixes that. I'm not really sure how/if that's related to the original issue, but it does help with the linking problem in my case so I'm leaving a note here in case anyone is running into a similar issue:
```bash
export LIBRARY_PATH="/usr/local/lib"
```