class library: don't warn by default when sending SynthDef
supercollider/supercollider pull request #5236
Opened 2020-11-06 13:05 UTC by telephon

## Purpose and Motivation

Currently, the warning:

```
WARNING:  SynthDef lalala too big for sending. Retrying via synthdef file
```

is more irritating than useful. This patch removes it in the default case.

An option is left to switch it on for debugging purposes.

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

2020-11-06 23:38 UTC, jamshark70 requested changes
As for the content, this makes sense to me (and it doesn't cancel the warning for non-local servers, good).

However, there's a stray portaudio submodule update, which is not on topic for the PR -- remove that and I'd approve.

2020-11-07 08:46 UTC, brianlheim commented
thanks for this! the new method also needs documentation.

2020-11-07 09:01 UTC, telephon commented
I've tried, but failed:
```
$ git submodule update
fatal: reference is not a tree: a63ed32b997abb2f7791bd8931d5a866e0f9c16e
Unable to checkout 'a63ed32b997abb2f7791bd8931d5a866e0f9c16e' in submodule path 'external_libraries/portaudio/portaudio_submodule'
```

2020-11-07 09:15 UTC, brianlheim commented
@telephon the hash you committed isn't in my clone of the repo, maybe it's a local commit or you are pointed at the wrong remote?

this will reset the whole submodule, i think:

```
git submodule deinit -f external_libraries/portaudio/portaudio_submodule/
git submodule sync external_libraries/portaudio/portaudio_submodule/
git submodule update --init external_libraries/portaudio/portaudio_submodule/
```

2020-11-07 09:16 UTC, brianlheim commented
> this will reset the whole submodule, i think

and i mean reset the whole thing, you should make sure you don't have any important unpushed work in the submodule directory.

2020-11-08 13:04 UTC, telephon commented
thanks a lot! (I'm amased you find the time for it)


The last line fails:
```
git submodule update --init external_libraries/portaudio/portaudio_submodule/
```

```
fatal: reference is not a tree: a63ed32b997abb2f7791bd8931d5a866e0f9c16e
Unable to checkout 'a63ed32b997abb2f7791bd8931d5a866e0f9c16e' in submodule path 'external_libraries/portaudio/portaudio_submodule'
```

2020-11-08 20:36 UTC, brianlheim commented
maybe you can just make a new branch off develop instead. what did you do to get things that way btw?

2020-11-09 08:09 UTC, telephon commented
hm, I have to admit that I did nothing. The same error happens when I try to update the `develop` branch.

When I delete the whole external libraries folder, the same thing happens with a different submodule:

```
$> rm -r external_libraries
$> git submodule update
Submodule path 'external_libraries/hidapi': checked out 'd1c0c5ff25c53850fcea0dbb4c8f9848dfd5cebc'
Submodule path 'external_libraries/link': checked out 'c1449edb28ccba86396a46a9989b8795960160a9'
Submodule path 'external_libraries/nova-simd': checked out '2bdc68bc5704a42578300a4c18411df2405cb307'
Submodule path 'external_libraries/nova-tt': checked out '55da93741e76632579b63004d3378139e32d634f'
fatal: reference is not a tree: a63ed32b997abb2f7791bd8931d5a866e0f9c16e
Submodule path 'external_libraries/yaml-cpp': checked out '728e26e42645d4d70ca65522990f915f47b47a50'
Unable to checkout 'a63ed32b997abb2f7791bd8931d5a866e0f9c16e' in submodule path 'external_libraries/portaudio/portaudio_submodule'
```

And then, a third time, it worked. So maybe it is a github network issue?

But while I continue all this, I realise that the whole local repository is messed up. Probably I need to start from scratch, but I don't want to lose all the pending topic branches.

2020-11-09 08:09 UTC, closed without merging

2020-11-09 12:22 UTC, brianlheim commented
@telephon oh i think i might see the issue? git may have been trying to checkout that hash from the assembla repo instead. it is hard to debug ephemeral filesystem and source control problems remotely, sorry i couldn't help more.

> I realise that the whole local repository is messed up.

howso?

> Probably I need to start from scratch, but I don't want to lose all the pending topic branches.

you can push branches to your remote to save them, or save them as patch files. if it's only a few branches that are messed up and that you want to synchronize to upstream, that is easy to do without re-cloning the entire repository (`git reset --hard` to the corresponding upstream branch, so for example `git checkout develop; git reset --hard upstream/develop`). and then for the branches that are wrong, rebase.

2020-11-10 09:59 UTC, telephon commented
>> I realise that the whole local repository is messed up.

> howso?

It's a bit hard to explain. I've managed to fix it I think. Thanks again!