docs: Add description to undocumented methods of the Integer class.
supercollider/supercollider pull request #5398
Opened 2021-03-21 16:56 UTC by mttvn

## Purpose and Motivation

Add description to undocumented methods of the Integer class.

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

2022-02-20 20:49 UTC, joshpar approved these changes

2022-02-20 20:51 UTC, joshpar commented
closing to reopen to rerun CI tests

2022-02-20 20:51 UTC, joshpar commented
Reopening

2022-09-13 20:02 UTC, dyfer commented
@joshpar @jrsurge are we waiting for further review or is this good to be merged?

2022-09-15 06:41 UTC, telephon requested changes

2022-09-15 06:41 UTC, telephon commented on HelpSource/Classes/Integer.schelp
> +0.clip(2,5); // returns 0
should be 
`0.clip(2,5); // returns 2`

2022-09-15 06:41 UTC, telephon commented on HelpSource/Classes/Integer.schelp
> +method::archiveAsCompileString
This method is part of an interface that is not documented for any class. Maybe lik to code::Classes/Archive:: ?

(but I don't mind).

2022-10-24 21:58 UTC, dyfer commented
I'm going to push a commit addressing the review

2022-10-24 22:11 UTC, dyfer commented
@telephon please let me know if this is good now. I decided to hide the `archiveAsCompileString` method in the help.

2022-10-26 19:47 UTC, merged