Fix bad argTemplate in Buffer.getn
supercollider/supercollider pull request #5460
Opened 2021-05-24 22:38 UTC by stevearc

## Purpose and Motivation

There is a bug in `Buffer.getn` that causes it to not call the `action` if the index passed in is a float. This happens because the OSC message generated casts the value to an integer, but the `argTemplate` does not.

#4598 did a large pass over the Buffer methods to try to make them all properly cast to integer in the right places, but it appears that this location was missed.

To repro the issue (and verify that it is fixed):
```sc
(
s.boot;
s.waitForBoot({
  b = Buffer.alloc(s, 10);
  s.sync;
  b.getn(0.0, 10, {|msg| msg.postln}); // Doesn't print anything without this fix
});
)
```

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [ ] This PR is ready for review

2021-05-24 23:03 UTC, joshpar requested changes
More of a light request than a hard one. This is a great catch - thanks! Can you please include a couple of tests for this? One for passing in a float and another for an integer, and finally some garbage like a string that we would expect to fail?

2021-05-26 02:43 UTC, stevearc commented
@joshpar Thanks for the review! I've added a regression test to `TestBuffer_server` to handle the float case. There's a test right above it that handles the integer case. I'm not convinced that we should add a test for passing in garbage, since the behavior in that case is undefined. Since there's no explicit contract it feels wrong for a test to be enforcing anything, but I could be convinced otherwise.

2021-05-26 04:37 UTC, joshpar approved these changes

2021-05-26 04:37 UTC, joshpar commented
Thank you!

2021-05-26 06:07 UTC, merged