Fix argument string ellipsis
supercollider/supercollider pull request #5499
Opened 2021-07-11 17:33 UTC by telephon

## Purpose and Motivation

This fixes #5498. Ellipsis arguments didn't work before, and for all usual cases there tests have been added.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

2022-01-11 21:30 UTC, telephon commented
Open question: do we want function.flop to use `flopInterpret`? Disadvantage: slower in creation. Advantage: behaves exactly like the original in terms or argument passing.

2022-02-25 03:46 UTC, joshpar commented
> Open question: do we want function.flop to use `flopInterpret`? Disadvantage: slower in creation. Advantage: behaves exactly like the original in terms or argument passing.

@telephon - yes. I think it should. My gut says that methods like this aren't being called thousands of times per second... and even then if they are, the 'slower' still may not be a problem... So I suggest the change to function.flop.
However - we could also consider retaining the original method's implementation with a new method name (floptimized?). I don't really think that is necessary, but if the speed really is a concern it wouldn't be a bad approach. 

I vote for updating function.flop, then I'll approve and merge.

2022-02-25 03:47 UTC, joshpar requested changes
use makeFlopFuncString for function:flop

2022-02-26 22:13 UTC, telephon commented
ok, good – I'll do this.

2022-07-12 19:48 UTC, dyfer commented
Hello @telephon , any update on this?

2022-07-15 10:52 UTC, telephon commented
Thanks for returning to this. I'd like to do this in August.

2022-07-16 07:00 UTC, telephon commented
I've found a problem with ellipsis args, will try to fix asap.

2022-07-16 09:19 UTC, telephon commented
OK, that is resolved, ready for review.

2022-07-16 09:32 UTC, telephon commented
(I've updated the `Purpose and Motivation` text at the beginning).

2022-10-21 21:56 UTC, joshpar approved these changes

2022-10-21 21:56 UTC, merged