Plugins: Fix AudioControl and InFeedback processing for an extra cycle
supercollider/supercollider pull request #5601
Opened 2021-10-19 09:48 UTC by vitreo12

## Purpose and Motivation

I have noticed a weird behavior of the `AudioControl` and `InFeedback` UGens.

If you run this code, you'll notice that the last audio cycle will run twice, generating a "double" dropout:

```SuperCollider
(
s.waitForBoot({
	SynthDef(\test, {
		Out.ar(\out.ir(0), { SinOsc.ar(2) * EnvGen.ar(Env([1, 1], [0.2]), doneAction:2) })
	}).add;

	s.sync;

	~bus = Bus.audio(s);

	Pbind(
		\instrument, \test,
		\dur, 1,
		\out, ~bus.index,
		\addAction, \addToHead
	).play;

	~reader = { \in.ar }.play(args:[ \in, 'a' ++ ~bus.index]);

	{ In.ar(0) }.plot(0.5);
})
)
```

![image](https://user-images.githubusercontent.com/32070555/137885438-1df7ef74-dd2c-4386-9609-60098df08849.png)

This happens because the `AudioControl` UGen (as well as the `InFeedback` one) only check if the bus has been touched in the current audio cycle. In my opinion, it should probably take into consideration if the bus has been touched in the previous audio cycle aswell, in order to avoid this "repetition" effect.

This PR fixes this issue. It basically allows `AudioControl` and `InFeedback` to work just like `In` when the `~reader` `Synth` is later in the chain, and just like `InFeedback` when the `~reader` `Synth` is before in the chain (reading the previous audio cycle).

`Pbind (\addToHead) -> ~reader:`
![image (1)](https://user-images.githubusercontent.com/32070555/137885661-f84d1fd4-fcfe-4aae-a965-f07d191611cc.png)

`-> ~reader Pbind (\addToTail) ->:`
![image (2)](https://user-images.githubusercontent.com/32070555/137885694-5c87ced2-7420-4382-81a4-14f1639c84d3.png)

## Types of changes

- Bug fix

## To-do list

- [X] Code is tested
- [X] All tests are passing
- [X] Updated documentation
- [x] This PR is ready for review

2021-10-20 09:44 UTC, vitreo12 commented
Sure, I just added some tests. Let me know if they are enough :)

2022-01-08 14:33 UTC, telephon commented
I think these failing tests are just timeouts, @vitreo12. It would be good to get this working, perhaps you can see if there is something in your tests that causes it?

2022-01-08 18:18 UTC, vitreo12 commented
Hi @telephon! All the tests I have implemented complete on my local Linux build, I don't know why they would hang on MacOS. Could anyone with MacOS maybe try them out and report what is going wrong? 

The test class is called `TestIOUGens` and the functions are: `test_InFeedback_equals_In`, `test_AudioControl_equals_In`, `test_InFeedback_equals_delayed_In` and `test_AudioControl_equals_delayed_In`.

2022-02-09 21:13 UTC, dyfer requested changes
Hello @vitreo12 
I have a request regarding the tests: it seems that they use `Silence.ar`, which does not exist in the standard class library. Could you replace it with `Silent.ar`?

2022-02-09 21:14 UTC, dyfer commented
@telephon @joshpar aside from the tests, do the changes in this PR look good to you?

2022-02-10 09:31 UTC, vitreo12 commented
> Hello @vitreo12 I have a request regarding the tests: it seems that they use `Silence.ar`, which does not exist in the standard class library. Could you replace it with `Silent.ar`?

Sure, just pushed in the changes.

2022-02-13 18:41 UTC, telephon commented on testsuite/classlibrary/TestIOUGens.sc
> +            this.assertFloatEquals(data.sum, 0.0, "InFeedback is not equal to In", report:true);
The report should be clearer, something like: "InFeedback should be equal to In when no other signal has been written to its bus"

2022-02-13 18:45 UTC, telephon commented on testsuite/classlibrary/TestIOUGens.sc
> +                this.assertFloatEquals(data.sum, 0.0, "AudioControl is not equal to In", report:true);
I'd suggest the message to say: "AudioControl should be equal to In for read after write".

2022-02-13 18:49 UTC, telephon commented on testsuite/classlibrary/TestIOUGens.sc
> +    test_AudioControl_equals_delayed_In {
suggestion: `test_AudioControl_equals_In_for_write_after_read`

2022-02-13 18:50 UTC, telephon reviewed
I see only some changes to be done in the naming of tests and messages. This is a very important fix, thanks a lot.

2022-02-13 21:44 UTC, smrg-lm commented
**Please review if this change is necessary** or something else is failing because the given example is not good, it works as expected if the `test` ugen doesn't define a control input for the output bus, try replacing it by:

```
	SynthDef(\test, {
		Out.ar(0, SinOsc.ar(2) * EnvGen.ar(Env([1, 1], [0.2]), doneAction:2))
	}).add;
```

2022-02-13 22:08 UTC, vitreo12 commented
> **Please review if this change is necessary** or something else is failing because the given example is not good, it works as expected if the `test` ugen doesn't define a control input for the output bus, try replacing it by:
> 
> ```
> 	SynthDef(\test, {
> 		Out.ar(0, SinOsc.ar(2) * EnvGen.ar(Env([1, 1], [0.2]), doneAction:2))
> 	}).add;
> ```

That's because `AudioControl` or `InFeedback` are used for inner-Bus communication. With your code, you're just writing directly to the audio output.

2022-02-13 22:20 UTC, smrg-lm commented
@vitreo12 I was wrong testing and the alarms sounded, apologies.

2022-02-13 22:51 UTC, vitreo12 commented
@telephon I have changed the names accordingly :)

2022-02-13 23:35 UTC, dyfer approved these changes

2022-02-13 23:35 UTC, dyfer commented
Tests look good do me now.
@telephon feel free to merge if you're happy with the PR otherwise.

2022-02-14 02:23 UTC, smrg-lm commented
Apologies for being annoying, I was worried because the use case is wrong, because the order of execution, and it makes the issue smell, but it smells good so far. I hope I'm not mistaken again: this change creates a gap in the audio in the following situation which is maybe better than what was happening before.

```
(
SynthDef('source', { arg out, freq=220;
	Out.ar(out, SinOsc.ar(freq));
}).add;

SynthDef('input', { arg a_in;
	Out.ar(0, a_in);
}).add;
)

b = Bus.audio();
x = Synth('source', [out: b, freq: 440]);
y = Synth('input', [a_in: b.asMap]);
z = Synth('source', [out: b]);

z.free;  // one block gap before x writes again.
```
After:

![despues](https://user-images.githubusercontent.com/703536/153788905-f93ecf9f-6e78-461d-87ae-dea9a2d6cbae.png)

Before:

![antes](https://user-images.githubusercontent.com/703536/153788922-fcff9c92-8acc-4413-9dec-3a1ab896074b.png)

I'm not sure what could be the desired behavior in this particular case but the feedback was not intended to be used like this anyway.

2022-02-14 13:02 UTC, telephon commented
That is a good point. It is actually a bit tricky what the best behaviour should be.

Possibiities:

1. all audio is read with time delay (this accumulates in multiple routing)
2. all audio is read with time delay only if there is at least one writer downbus, otherwise without (this may cause a discontinuity if the downbus writer stops)
3. the audio from upbus is read with no time delay and the audio from downbus is read with time delay
4. once the inFeedback has received its flag that there are writers downstream, it should continue to play delayed, irrespective of whether the downstream writers ended.

2022-02-25 03:55 UTC, joshpar commented
As noted elsewhere, there likely isn't a way to satisfy ALL cases, but I do think this satisfies ones that make more sense than my initial implementation of this. I'm good approving it, but will wait until this weekend to merge in case @telephon or @dyfer feel like anything else can still be resolved.

2022-02-25 03:55 UTC, joshpar approved these changes

2022-02-27 12:49 UTC, telephon approved these changes

2022-02-27 19:13 UTC, merged