Classlib: Allow any type of text stream in the FileReader hierarchy
supercollider/supercollider pull request #5611
Opened 2021-11-13 01:24 UTC by jamshark70

## Purpose and Motivation

```
c = CollStream("5,7,hello,\"a comma, in quotes!\"");
r = CSVFileReader(c);

ERROR: Primitive '_FileOpen' failed.
Wrong type.
```

But... FileReader's interaction with the `stream` is, in total:

- `stream.reset` -- `CollStream` implements this
- `stream.getChar` -- `CollStream` implements this
- `stream.close` -- `CollStream` doesn't implement this, but we can use `tryPerform` to make it a no-op

So there is not a compelling reason why a FileReader must be accessing a file on disk and disallow a stream of characters in memory.

(Editorial: The usual OOP advice is to program toward interfaces rather than class hierarchies: `respondsTo` rather than `isKindOf`. This looks like a case where "oh, `isKindOf` will be fine just this once" except that it isn't, not really.)

Since the really relevant operation is `getChar`, this PR changes the FileReader constructor so that any object implementing `getChar` will be allowed as the stream.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [ ] Updated documentation -- Note that the entire FileReader hierarchy has spotty documentation. "Updated documentation" would require essentially a complete rewrite of four or five help files. I'm afraid at the moment I don't have time to do that. If someone is concerned about this, I would recommend opening an issue.
- [x] This PR is ready for review

2022-02-26 03:09 UTC, joshpar requested changes
request changes just for feedback on my comment - probably fine otherwise.

2022-02-26 22:17 UTC, telephon commented on SCClassLibrary/Common/Streams/TabFileReader.sc
> +	close { stream.tryPerform(\close) }
one could also implement `close {}` for the superclass `Stream`  to do nothing?

2022-02-27 19:08 UTC, joshpar commented on SCClassLibrary/Common/Streams/TabFileReader.sc
> +	close { stream.tryPerform(\close) }
I think the approach in the PR is correct

2022-02-27 19:10 UTC, joshpar approved these changes

2022-02-27 19:11 UTC, merged

2022-02-28 00:05 UTC, jamshark70 commented
Sorry, late to reply -- wrt "If tryPerform(\close) fails," tryPerform swallows *only* does-not-understand. It doesn't handle other errors. So this change will not cause other types of silent failure.

Thanks for the merge!

```supercollider
x = 1;

// tryPerform vs DoesNotUnderstandError

x.flurghle;  // Message 'flurghle' not understood.

x.tryPerform(\flurghle);  // no error

// tryPerform vs other errors

x.perform('+', 2);  // 3

x.perform('+', nil);  // binary operator '+' failed.

try { x.perform('+', nil) };  // nil (no error)

x.tryPerform('+', nil);  // binary operator '+' failed.
```