Find jack using cmake's FindPkgConfig
supercollider/supercollider pull request #5680
Opened 2022-01-02 16:37 UTC by dvzrv

## Purpose and Motivation

Replace the custom `find_package()` cmake integration for jack with the use of `pkg_check_modules()` (part of cmake's [FindPkgConfig](https://cmake.org/cmake/help/v3.12/module/FindPkgConfig.html)), as it is more straight forward to use this way and does not rely on inconsistent behavior due to calls to `find_path()` and `find_library()` (which disregard the output of pkg-config).

Fixes #5678

## Types of changes

- Bug fix

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

2022-01-02 17:36 UTC, dvzrv commented
The failure in the test suite seems unrelated to this PR.

2022-01-02 17:41 UTC, dvzrv commented
There are more uses of the legacy FindJack.cmake implementation in the portaudio submodule. I don't really know what to do about those yet, but maybe they can be fixed upstream and removed there as well.

2022-01-12 02:16 UTC, dyfer approved these changes
Thanks! Looks good to me. To test, I built with "ancient" Jack on macOS and still works fine.

I wonder if this changes anything on Windows but @sonoro1234 is probably the only person who knows/cares about that...

2022-01-12 08:37 UTC, sonoro1234 commented
I cant test now: laptop broken

2022-01-13 08:59 UTC, sonoro1234 commented
I think it should try to work without pkgconfig installed also.

2022-01-13 18:37 UTC, dyfer requested changes
After the comment from @sonoro1234 I also think it would be good to not fail if pkgconfig is not available (if I understand correctly that this is the current behavior?)

2022-01-13 19:18 UTC, dvzrv commented
After conversing with @falktx on this topic, he is of the opinion, that on Windows an application should not link directly against libjack.dll, but instead use `LoadLibrary` to wrap it.
The implementation that is about to be removed should therefore be replaced by something akin to https://github.com/DISTRHO/DPF/tree/develop/distrho/src/jackbridge on Windows, while it is completely fine to use pkgconfig in all other cases.

Related to this and seeing that there are no CI targets to even build against jack2 on Windows, could you elaborate on how this worked in the past, or whether this ever worked in the past? I have no Windows system to test on and am generally not really interested in the platform, so my question would also be: Is there even a support guarantee for it?

2022-01-13 19:36 UTC, dyfer commented
> (...)  on Windows an application should not link directly against libjack.dll, but instead use LoadLibrary to wrap it.

I agree that this would be optimal. There were some previous conversations about the different backends being a runtime option, where this would be needed anyway. However I don't see that we'll be implementing this shortly (although contributions are always welcome of course).

> Related to this and seeing that there are no CI targets to even build against jack2 on Windows, could you elaborate on how this worked in the past, or whether this ever worked in the past? I have no Windows system to test on and am generally not really interested in the platform, so my question would also be: Is there even a support guarantee for it?

There's no support guarantee and we do not test for this. IIUC correctly @sonoro1234 has used this configuration and knowing that I don't want to break his setup. However, I don't want to advocate for functionality that's too obscure either... If we can maintain some way of _optionally_ providing Jack include/library paths as cmake config flags I'd support that, but if everyone agrees that requiring `pkgconfig` is the right solution, I can be persuaded.

2022-01-13 20:11 UTC, dvzrv commented
>  However, I don't want to advocate for functionality that's too obscure either... If we can maintain some way of optionally providing Jack include/library paths as cmake config flags I'd support that, but if everyone agrees that requiring pkgconfig is the right solution, I can be persuaded.

It appears as if the direct linking against libjack.dll is not the right way to do it on Windows (but I am far from being an expert on that topic), so pkgconfig integration there would not necessarily help anyways I guess.
Given that the FindJack.cmake file introduces inconsistent behavior in regards to the assumptions made with plain pkgconfig integration and generally adds more complexity, I would still advocate for removing it. However, I can not estimate how much time and effort it would take to implement something for Windows, that uses `LoadLibrary` (disregarding the effort it would take to deal with a runtime selection of backends on all operating systems, as I believe that should really be a different topic).

In regards to the cmake config flags, I think it could be saner to use `find_library()` etc. on Windows specifically instead (although [pkgconf](https://github.com/pkgconf/pkgconf/) can also be built for Windows AFAIK - @sonoro1234 did you ever use that for header/library detection on Windows?), but leave a note, that it should be replaced with `LoadLibrary` in the future.

2022-01-13 20:18 UTC, sonoro1234 commented
> did you ever use that for header/library detectio

Never

2022-01-13 21:43 UTC, dvzrv commented on cmake_modules/FindJack.cmake
> -      ${_JACK_LIBDIR}
@sonoro1234 is this how you would provide the search path on Windows for this? e.g. `cmake -D _JACK_LIBDIR=/path/to/jack -D _JACK_INCLUDEDIR=/path/to/jack`?

2022-01-22 15:12 UTC, sonoro1234 commented
Got new laptop:

Building for AUDIOAPI jack:

```
-- Audio API (scsynth): jack
-- Found fftw3f: C:/supercolliderrepos/x86/fftw/libfftw3f-3.dll
-- FFT library (supernova): FFTW
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/cmakes/cmake-3.16.3-win64-x64/share/cmake-3.16/Modules/FindPkgConfig.cmake:511 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  C:/cmakes/cmake-3.16.3-win64-x64/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  server/supernova/CMakeLists.txt:152 (pkg_check_modules)


-- Audio API (supernova): jack
-- Configuring incomplete, errors occurred!
```

2022-01-22 15:32 UTC, dvzrv commented
> Got new laptop:
> 
> Building for AUDIOAPI jack:

For the sake of the argument, can you try again after installing [pkgconf](https://github.com/pkgconf/pkgconf/#compiling-pkgconf-and-libpkgconf-with-cmake-usually-for-windows)?

2022-01-22 16:25 UTC, sonoro1234 commented
> For the sake of the argument, can you try again after installing [pkgconf](https://github.com/pkgconf/pkgconf/#compiling-pkgconf-and-libpkgconf-with-cmake-usually-for-windows)?

I guess it could work, but the point is: I was able to build without pkgconf earlier, why having an extra dependency is seen as an improvement?

I never have need pkgconf for  building any program in windows.

I think it should try to work without pkgconfig installed also. (In case it is not found, try with find_package)

2022-01-22 18:23 UTC, dyfer commented
@dvzrv would it be possible to make a change so that jack include/library paths can be passed as cmake config flags, in which case pkgconfig is not used?

2022-01-23 16:27 UTC, dvzrv commented
> @dvzrv would it be possible to make a change so that jack include/library paths can be passed as cmake config flags, in which case pkgconfig is not used?

Yes, I'll look into that as soon as time permits. It shouldn't require a lot of changes though I hope.

2022-04-27 19:43 UTC, dyfer commented
Hello @dvzrv 
I wanted to loop back to this, would you be able to look into finishing this PR?

2022-07-12 19:47 UTC, dyfer commented
Hello @dvzrv, I wanted to loop back on this. We might be gearing up for new release (RC) in the next few weeks (TBD), are you planning to work on this PR?

2023-01-02 19:09 UTC, dyfer commented
Any update on this @dvzrv ?

2023-01-11 13:46 UTC, dvzrv commented
> Any update on this @dvzrv ?

@dyfer Sorry, I have forgotten about this.

I have now rebased and included a hack for Windows (also adding a NOTE), which allows setting `JACK_LINK_LIBRARIES` and `JACK_INCLUDE_DIRS` via providing the `_JACK_LINK_LIBRARIES` and `_JACK_INCLUDE_DIRS` options to cmake.

@sonoro1234 This will require testing on your side, but it worked for me when testing on Linux (without the check for `WIN32` of course). My assumption this should "just work", but I think this is rather hacky and as noted by jack upstream should not be done this way. If you have time adding a proper weakref solution for windows in the future (plus CI integration), that'd be ace!

2023-01-11 21:31 UTC, dyfer commented on server/scsynth/CMakeLists.txt
> +  # NOTE: this is a hack for Windows, which should rely on a weakref link against jack instead
IMO the suggestion here is only one of possible solutions.
IIUC, the workaround (or hack, whatever) is provided to be able to build with jack _without relying on PkgConfig_. While regular linking might be suboptimal on Windows, it should technically work at least when building and running locally. And even if weak linking was used, we'd still need to provide jack headers, which might also need to be found somehow, if they are not provided with the library that provides weak linking.

This is not very important and the comment can stay as is. However, IMO, a more accurate note would state something like `this is a workaround for Windows if PkgConfig is not available`

2023-01-11 21:56 UTC, dyfer approved these changes
I managed to build this on Windows with MinGW 8.1 using following cmake invocation:
```
cmake -G "MinGW Makefiles" -D SUPERNOVA=OFF -D SC_USE_QTWEBENGINE=OFF -D AUDIOAPI=jack -D _JACK_LINK_LIBRARIES="c:/Program Files/JACK2/lib/libjack64.lib" -D _JACK_INCLUDE_DIRS="c:/Program Files/JACK2/include" ..
cmake --build . --config RelWithDebInfo --target install
```
I couldn't then run scsynth as I was getting an error, but it looks like this has something to do with my build environment, as I got the same result when building with PortAudio backend (and still MinGW):
```
>Install\SuperCollider\scsynth.exe -u 57110
Mingw-w64 runtime failure:
  VirtualProtect failed with code 0x677
```
Since this seemed to build fine, and we can't even build with jack backend with MSVC (due to dependency on `sys/time.h` I think), and the build I attempted completed, I assume this is enough to make it work for those who need it.

I'll wait a bit in case @sonoro1234 has any input on this and I'll plan to merge it in a day or two.

2023-01-12 10:35 UTC, dvzrv commented
Will reschedule the failing tests. I believe they are flaky (as I only changed the comment...).

2023-01-12 10:38 UTC, dyfer commented
Yes, no worries about these test, the failure is not related to this PR. One day we might improve reliability of the test suite...
Thanks again for the PR!

2023-01-16 15:28 UTC, dyfer commented
Merging. Thanks so much @dvzrv !

2023-01-16 15:28 UTC, merged