Topic/fix funcdef help method name
supercollider/supercollider pull request #5999
Opened 2023-03-25 13:34 UTC by telephon

Just a small helpfile fix.

2023-04-02 17:30 UTC, nhthn commented on HelpSource/Classes/FunctionDef.schelp
> +f = { |x=1, y=0| x.squared + y.squared }; // some function with arguments
whitespace around `=` would be nice

2023-04-02 17:41 UTC, nhthn requested changes
whitespace around = would be nice

2023-04-02 20:59 UTC, telephon commented
I don't quite understand what you mean.

2024-05-03 21:45 UTC, adcxyz commented
The only = signs are in line 127, 
```f = { |x=1, y=0| x.squared + y.squared }; // some function with arguments```
so probably it should be
```f = { |x = 1, y = 0| x.squared + y.squared }; // some function with arguments```

2024-08-30 09:37 UTC, capital-G commented on HelpSource/Classes/FunctionDef.schelp
> +f = { |x=1, y=0| x.squared + y.squared }; // some function with arguments
```suggestion
f = { |x = 1, y = 0| x.squared + y.squared }; // some function with arguments
```
I think this is what @nhthn suggested.

2024-08-30 09:37 UTC, capital-G commented
Bump @telephon

2025-04-02 17:20 UTC, elgiano commented
Looks like this was superseded by #6029

2025-04-02 17:20 UTC, closed without merging