Fix UGen initialization: LFUGens pt. 2/3
supercollider/supercollider pull request #6172
Opened 2023-12-30 18:58 UTC by mtmccrea

## Purpose and Motivation
A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).

#### This fixes the initialization of a batch of `LFUGens`:
- `VarSaw`: properly reset state on initialization
- `T2A`: fix initialization, clip offset to buflength
- `InRect`: check input rates on x and y, init is OK
#### Cleanup
- `LinExp`: remove repeated code from `LinExp_SetCalc`
- `Wrap`, `Trapezoid`: remove commented-out code
- `Unwrap`:  add note re: missing class definition
#### Documentation was added to:
- `VarSaw`, `SyncSaw`, `T2K`, `T2A`, `InRect`, `InRange`
#### UGens reviewed and tested, no fix needed:
- `A2K`, `DC`, `Clip`, `Wrap`, `Fold`, `ModDif`

(fixed Issues will be updated here)
- Fixes #4228

## Types of changes

- Documentation
- Bug fix
- Breaking change - changes are technically breaking for the first output sample (or, e.g., a one-sample phase change from previously)

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

2024-06-19 12:43 UTC, mtmccrea commented
@JordanHendersonMusic Seeing the squashed diff from that first LFUGens init sample fix PR made it more clear what you were seeing wrt adding `const` to changed code...

So, because this PR is still in the family/source of that companion PR, I've added `const` in to those instances and the ones local to this batch of changes in the [most recent commit](https://github.com/supercollider/supercollider/pull/6172/commits/8aab6836e815791ed05ca23bc3c05d805ffc66c1) to see if it would make sense in context. It still seems a bit "random" in the larger context, unless the scope of that particular type of change is expanded— only local changes -> all Ctors? -> the whole file? Then we have a single file specifying const vars among the whole library of UGens that don't. 

Thoughts?

2024-06-19 13:56 UTC, JordanHendersonMusic commented
I wouldn't touch something just to add const, unless it was in a commit by itself so it can be added to the blame ignore list.

I don't think having a single file or function with consts is a problem, it only changes how you read and think about the function by making things easier. It's not a fundamental difference in style or anything.

2024-06-21 10:27 UTC, mtmccrea commented
I added tests for the UGens to which there are functional changes, `VarSaw` and `T2A`, anticipating the request ;)
So this is ready for review!

2025-04-16 16:51 UTC, mtmccrea commented
Pinging @joshpar for potential review,

and @dyfer requesting this be added to the 3.14 milestone.

It's been waiting in the wings for a while, and generally the init sample fixes build on each other, so would be great to get this in :)

2025-04-16 18:15 UTC, dyfer commented
Thanks @mtmccrea 
Could you please resolve conflicts in this PR?

2025-04-17 13:32 UTC, mtmccrea commented
> Could you please resolve conflicts in this PR?

Done, thanks! Re-running failed jobs, though that may be a bigger CI issue...

2025-04-18 11:56 UTC, elgiano requested changes
I had a good read of all of this and tested it, it looks all right to me, I only had a couple of questions.

Thanks for the great work!

2025-04-18 11:56 UTC, elgiano commented on server/plugins/LFUGens.cpp
> +    double phase = unit->mPhase = sc_clip(static_cast<double>(ZIN0(1)), 0.0, 1.0);
I wonder if we should wrap it instead, so that an initial phase of 1.5 becomes 0.5. It would produce a more similar result to what the unit does now (minus the init value glitch you fixed).

Alternatively, we should write more explicitly in schelp that the value is clipped.

2025-04-18 11:56 UTC, elgiano commented on HelpSource/Classes/T2K.schelp
> +Once running, however, its first output sample will be a trigger if one is received within the first block.
I'm having a hard time understanding these two sentences. Let's perhaps try to rephrase it and add a couple of examples?

2025-04-18 22:47 UTC, mtmccrea commented on HelpSource/Classes/T2K.schelp
> +Once running, however, its first output sample will be a trigger if one is received within the first block.
Thanks! I've updated the description, hopefully this reads more clearly.

Regarding examples, I don't think it's necessary, as it's quite a fringe case, and in the rare case that anyone encounters it, this Discussion would be sufficient to tell them what's going on IMO. Let me know though if you disagree!

2025-04-18 22:47 UTC, mtmccrea commented on server/plugins/LFUGens.cpp
> +    double phase = unit->mPhase = sc_clip(static_cast<double>(ZIN0(1)), 0.0, 1.0);
Good call, updated!

2025-04-19 02:19 UTC, elgiano approved these changes

2025-04-19 02:19 UTC, merged