improve/fix plugin unloading
supercollider/supercollider pull request #6191
Opened 2024-01-11 23:48 UTC by Spacechild1

## Purpose and Motivation

scsynth and supernova already try to unload plugins by searching for an "unload" function. However, this is not documented in the plugin API yet.

Changes:

* add `PluginUnload` macro to `SC_InterfaceTable.h`, so it can be easily used by third-party plugins

* use `PluginUnload` macro for the DiskIO and UI UGens (which actually had a wrong function signature!)

* unload static plugins

* don't forget to call `LoadLibrary()` resp. `dlclose()` in scsynth

## Types of changes

- Bug fix
- New feature

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

2024-01-11 23:53 UTC, Spacechild1 commented
@dyfer I've followed the existing formatting, but the linter doesn't like it. What should I do?

2024-01-24 20:06 UTC, mtmccrea commented
I linted your changes and there's just some minor formatting changes needed. You'll just need to [run clang-format](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions).

2024-01-24 20:10 UTC, mtmccrea commented
If you don't yet have it set up and want to just get tests to pass, here's what the formatted changes look like:

https://github.com/supercollider/supercollider/commit/243e51f06c994a1ec036c7c809b1e03a27f688f0

But for future contributions you'll definitely want to have it set up.

2024-01-24 20:40 UTC, Spacechild1 commented
> I linted your changes and there's just some minor formatting changes needed. You'll just need to [run clang-format](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions).

I am aware of that. Anyway, I just shut up and do what the linter tells me :)

2024-08-30 11:57 UTC, Spacechild1 commented
This is only adds a macro, so there is no API/ABI break.

Plugin API/ABI breaks only happen if you modify one of the public structures (e.g. `World`)  or add functions to the interface table (see also https://github.com/supercollider/supercollider/issues/5347).

2024-08-30 13:08 UTC, JordanHendersonMusic commented
> modify one or more public structures (e.g. World) by adding/removing members or changing their types [ABI/API break]

I think reordering the members also counts as an ABI break?

2024-08-30 19:35 UTC, Spacechild1 commented
> I think reordering the members also counts as an ABI break?

Yes! That's very important! I forgot to mention that. Thanks for pointing this out.

2024-10-10 16:39 UTC, Spacechild1 commented
@capital-G @JordanHendersonMusic Can we merge this?

2024-10-10 16:42 UTC, capital-G commented
I don't have any objections if this does not touch the ABI - but I don't have enough expertise (regarding C interfaces) to give this a review.

2024-10-10 17:32 UTC, JordanHendersonMusic requested changes
This looks good and everything makes sense. Thanks! 

I've got a little comment/suggestion, but it's just a small thing.

Otherwise, were you going to add some documentation for this feature?

2024-10-10 17:32 UTC, JordanHendersonMusic commented on server/scsynth/SC_Lib_Cintf.cpp
> +
Can you think of any way to avoid manually specifying all the ugens to unload?

For a non-static library you don't have to do anything, but you have to do this extra step for static ones, which seems likely to be forgotten, leading to odd bugs.

I can't think of a nice way (even with context magic), so perhaps some comments warning users to add it here?

2024-10-10 17:55 UTC, Spacechild1 commented on server/scsynth/SC_Lib_Cintf.cpp
> +
> Can you think of any way to avoid manually specifying all the ugens to unload?

Unfortunately, no. Note that you also have to explicitly call all the `*_Load()` functions, so this issue is not specific to this PR.

2024-10-10 17:58 UTC, Spacechild1 commented
> Otherwise, were you going to add some documentation for this feature?

Well, the whole plugin API is completely uncommented. IMO there should be doxygen comments in all the public API headers, but this is out of scope for this PR :)

2024-10-10 18:06 UTC, JordanHendersonMusic commented
Unless there is a place where load is mentioned and unload isn't, personally, I wouldn't bother for now.

2024-10-10 18:51 UTC, Spacechild1 commented
I've just added a small subsection to https://doc.sccode.org/Guides/WritingUGens.html.

2024-10-11 08:39 UTC, JordanHendersonMusic commented on server/scsynth/SC_Lib_Cintf.cpp
> +
Hm, I'm actually quite confused by this STATIC_PLUGINS flag.

Seems it doesn't work and needs plugin sources added to the cmake file to work?
https://github.com/supercollider/supercollider/issues/5224#issuecomment-752701112

Also, it seems it is only needed for wasm, which we don't support any way.

So perhaps this flag could just be removed?

...but that's beyond this PR.

2024-10-11 08:40 UTC, JordanHendersonMusic commented on server/scsynth/SC_Lib_Cintf.cpp
> +
What do you think @Spacechild1, have I understood this correctly? If so, I'll make an issue and approve this.

2024-10-11 11:05 UTC, Spacechild1 commented on server/scsynth/SC_Lib_Cintf.cpp
> +
> Seems it doesn't work and needs plugin sources added to the cmake file to work?

Ah yes. In fact, we would need a CMake option that if set to `TRUE` adds a `STATIC_PLUGINS` compile definition and adds all plugin sources to the main executable. FWIW I have opened a feature request: https://github.com/supercollider/supercollider/issues/6505

> Also, it seems it is only needed for wasm, which we don't support any way.

Well, there is already a working proof-of-concept for running scsynth in the browser, so it's definitely something we should keep. In fact, it is useful for all platforms that don't support dynamic plugin loading or don't allow to ship shared libraries (e.g. iOS).

2024-10-11 11:07 UTC, JordanHendersonMusic commented on server/scsynth/SC_Lib_Cintf.cpp
> +
Thanks!

2024-10-11 11:07 UTC, JordanHendersonMusic approved these changes

2024-10-11 11:12 UTC, Spacechild1 commented
Anyone wants to merge this? Maybe @telephon, @dyfer or @muellmusik?

2024-10-11 13:11 UTC, merged