Buffer docs: update send/loadCollection examples
supercollider/supercollider pull request #6258
Opened 2024-04-20 11:45 UTC by mtmccrea

## Purpose and Motivation

This is a trivial documentation change for the sake of illustrating the PR process for a tutorial. So I might as well submit it :)

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

2024-04-22 13:45 UTC, JordanHendersonMusic requested changes
Hi, thanks for this, and the upcoming documentation! 

This looks good, but I think you have missed a couple of spaces.

2024-04-22 13:45 UTC, JordanHendersonMusic commented on HelpSource/Classes/Buffer.schelp
>  a = Array.fill(2000000,{ rrand(0.0,1.0) });
missing spaces after comma

2024-04-22 13:45 UTC, JordanHendersonMusic commented on HelpSource/Classes/Buffer.schelp
> +a = Array.fill(2000000, { rrand(0.0,1.0) }); // a LARGE collection
and here inside the `rrand`

2024-04-22 13:45 UTC, JordanHendersonMusic commented on HelpSource/Classes/Buffer.schelp
>  		DiskIn.ar( 1, bufnum )
This line (261) has extra spaces in.

2024-04-22 13:45 UTC, JordanHendersonMusic commented on HelpSource/Classes/Buffer.schelp
> +SynthDef(\help_Buffer,{ |out = 0, bufnum|
A missing space after comma

2024-04-22 13:45 UTC, JordanHendersonMusic commented on HelpSource/Classes/Buffer.schelp
>  	Out.ar( out,
here is and extra space after the parentheses.

2024-04-22 15:26 UTC, JordanHendersonMusic approved these changes

2024-04-22 15:41 UTC, JordanHendersonMusic commented
> all the code style issues

Across all the docs? ...that sounds like a herculean task! Might be worth asking on the forum if other people might be interested in take a file or two - good chance to get some new contributors?

Do you think I should merge this? The wiki says a third person isn't needed in the case of doc changes like this, and that new reviewers shouldn't merge (which I am).

2024-04-22 16:19 UTC, mtmccrea commented
> Across all the docs? 

Haha no... _but_ funny you should mention it, I have slipped down a bit of a rabbit hole with search and replace throughout the docs and it seems somewhat feasible. I've already [swept a few rules through](https://github.com/mtmccrea/supercollider/tree/topic/docs-code-style-update) a few hundred files—it's not foolproof, and not fully automatic, but doable I think. If it's looking ok after a bit more hacking, I may post it as a PR just for feedback to gauge interest.

> Do you think I should merge this?

Let's hold off for now, I think "Trusted Reviewers" are the ones that merge (I don't do this myself). I've been meaning to post a question on the forum Development Topic to get some clarity on these details (and update the wiki with the info...)

2024-05-05 15:21 UTC, adcxyz approved these changes
looks good!
in lines 259 and 296, you are still missing a space between comma and curly brace:
SynthDef(\help_Buffer_cue,{ |out = 0, bufnum|

2024-05-06 06:47 UTC, mtmccrea commented
Thanks for catching those! Updated.

2024-05-11 19:44 UTC, mtmccrea commented
Since there are two approvals on this, I'll go rogue and merge my own PR 😈

2024-05-11 19:44 UTC, merged