Add that the index starts at 0 to the documentation for SequenceableCollection, Array, ArrayedCollection and List.
supercollider/supercollider pull request #6536
Opened 2024-11-16 01:21 UTC by prko

## Purpose and Motivation

"starting from 0" is added to the summary and description to make SequenceableCollection indexing easy to understand for the novice.
I am not sure if every subclass documentation should include "integer starting from 0".
Please let me know it.

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

2024-11-16 09:00 UTC, capital-G approved these changes
I think this is a good addition, yet I think no novice will come across the documentation of this more advanced/hidden class.

I think `List` or `Arary` could also include this information, or also `.at` https://docs.supercollider.online/Classes/List.html#-at

2024-11-16 14:59 UTC, prko commented
I have added the same explanation to the documentation for Array, ArrayedCollection and List. The form of the text varies depending on the context.

2024-11-18 12:04 UTC, telephon requested changes
All this can be a little bit subtle, as you can see from my comments – you need to carefully check what is the case. I would leave away any mention of the class of an input object, beacause this is a separate issue, or extend the issue to document the less well known cases, which would be useful.


Now that I think of it, you could also make a separate tutorial named "indexing collections", where all this is explained.

2025-02-21 07:49 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Put strong::item:: at strong::index::, specified as an integer starting from 0, replacing what is there.
thanks, done!
I also added corresponding examples.

2025-02-21 07:49 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
>  code::
I am glad there is at least one thing I know for sure!

2025-02-21 07:49 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
>  code::
thanks, done!
I also added corresponding examples.

And, I changed here the term `element` to `item` according to your opinion in https://github.com/supercollider/supercollider/pull/6537#issuecomment-2482855952

2025-02-21 07:50 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Inserts the item into the contents of the receiver at the specified index, which is an integer starting from 0. This method may return a new ArrayedCollection. For this reason, you should always assi
I am glad there are at least two things I know for sure!

2025-02-21 07:50 UTC, prko commented on HelpSource/Classes/List.schelp
> +Return the item at strong::index::. See link::#Index starting from 0::.
Could you reconsider it? 
`See Index starting from 0`is very short. 

A newbie can easily find the thing with this link. Otherwise, if the reader is not familiar with it, he or she will have to search the document more, and that is not beginner-friendly.
With this link, readers who reach this section by searching for `.at' do not have to scroll through the whole document...

2025-02-21 07:50 UTC, prko commented on HelpSource/Classes/SequenceableCollection.schelp
> +summary::Abstract superclass of collections indexable by integers starting from 0
Done. 
The previous explanation `integer indexable collection` is also incorrect. I think the following is better:
summary::Abstract superclass of indexable collections

2025-02-21 07:50 UTC, prko commented on HelpSource/Classes/SequenceableCollection.schelp
> +SequenceableCollection is a subclass of Collection whose elements can be indexed by an Integer starting from 0. It has many useful subclasses; link::Classes/Array:: and link::Classes/List:: are among
Done. 
The previous explanation `integer indexable collection` is also incorrect. I think the following is better:
SequenceableCollection is a subclass of Collection whose items can be indexed.

And, I changed here the term `elements` to `items` according to your opinion in https://github.com/supercollider/supercollider/pull/6537#issuecomment-2482855952

2025-02-21 07:50 UTC, prko commented on HelpSource/Classes/List.schelp
Could you reconsider it? 
`See Index starting from 0`is very short. 

A newbie can easily find the thing with this link. Otherwise, if the reader is not familiar with it, he or she will have to search the document more, and that is not beginner-friendly.
With this link, readers who reach this section by searching for `.put' do not have to scroll through the whole document...

2025-02-21 07:51 UTC, prko commented on HelpSource/Classes/List.schelp
>  method::removeAt
Could you reconsider it? 
`See Index starting from 0`is very short. 

A newbie can easily find the thing with this link. Otherwise, if the reader is not familiar with it, he or she will have to search the document more, and that is not beginner-friendly.
With this link, readers who reach this section by searching for `.removeAt' do not have to scroll through the whole document...

2025-04-15 18:05 UTC, dyfer commented
@telephon @prko can we push this towards merging?

@prko sorry, we have conflicts now that need to be resolved.

2025-04-15 19:49 UTC, telephon commented on HelpSource/Classes/List.schelp
> +Return the item at strong::index::. See link::#Index starting from 0::.
ok, if you like, it doesn't hurt. But let'S nor put it everywhere ok ? :)

2025-04-15 19:51 UTC, telephon commented on HelpSource/Classes/SequenceableCollection.schelp
> +SequenceableCollection is a subclass of Collection whose elements can be indexed by an Integer starting from 0. It has many useful subclasses; link::Classes/Array:: and link::Classes/List:: are among
Yes, better. But actually, it can be indexed by any SimpleNumber: `[1, 2, 3].at(0.5) // -> 1`

2025-04-15 19:53 UTC, telephon commented on HelpSource/Classes/List.schelp
I don't know how this link-thing works, but if you think it will help, you can go ahead, yes.

2025-04-16 01:23 UTC, prko commented
I have resolved the conflicts. From my perspective, everything is ready to be merged as-is, unless others have further suggestions or would like to propose additional changes to this PR.

2025-04-16 11:08 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Return the item at strong::index::, which is specified as an integer starting from 0.
I missed a thing and did in https://github.com/supercollider/supercollider/pull/6536/commits/a24373a97741e4281110339c60a051192d02cf63

2025-04-28 01:24 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +link::Classes/ArrayedCollection:: is an abstract class, a subclass of link::Classes/SequenceableCollection:: whose items are held in a vector of slots, indexable by link::Classes/SimpleNumber:: start
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/21912de98a32b705d32088b4788c8a943f26de62.

2025-04-28 01:24 UTC, prko commented on HelpSource/Classes/SequenceableCollection.schelp
> +summary::Abstract superclass of indexable collections by SimpleNumber
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/21912de98a32b705d32088b4788c8a943f26de62.

2025-05-06 18:42 UTC, dyfer commented
@telephon is this good to merge now?

2025-05-27 00:20 UTC, dyfer commented
@prko this PR now has conflicts with the `develop` branch, sorry. Would you be able to resolve the conflicts?

2025-05-28 11:06 UTC, mtmccrea reviewed
Thanks for this, @prko. In general, I think there is too much emphasis on float indices. Rather than comment on each case, I've highlighted a few.

I think to have so many examples with float indices can be confusing/misleading and that it's enough to have one set of examples with outlier indexing cases (floats, negative or out-of-range values). You could then linked to those from descriptions where this behavior is mentioned. Similar I suppose to @telephon's suggestion for an indexing tutorial, or following the same approach you used with anchoring to the `Index starting from 0` description.

2025-05-28 11:06 UTC, mtmccrea commented on HelpSource/Classes/ArrayedCollection.schelp
> +Put strong::item:: at strong::index:: starting from 0, specified as an integer or float, or even array of float, replacing what is there.
I'd recommend de-emphasizing use of floats:
```
Put strong::item:: at strong::index:: starting from 0, replacing what is there. strong::index:: can be an array of indices. If a float is used as index, it will be truncated.
```
or similar.
This same approach could be used in other places where this point is repeated.

2025-05-29 03:27 UTC, prko commented on HelpSource/Classes/Array.schelp
> +Arrays use 0-based indexing, meaning the first item is accessed with index 0. Therefore, the index 2 in code::a.put(2, obj)::, code::a.at(2)::, and code::a[2]:: refers to the third item, counting fro
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/b851561fdd38e8719f856ef62b107f48689e2da5.

2025-05-29 03:27 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +z = x.put([0.5, 1], 150); // [150, 150, 3]
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/b851561fdd38e8719f856ef62b107f48689e2da5.

2025-05-29 03:28 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +x[(-1.1, 0 .. 3.3)];              // same as above (syntactic shortcut)
Thanks! I intended to show the three various writing styles comparatively.  Done in https://github.com/supercollider/supercollider/pull/6536/commits/b851561fdd38e8719f856ef62b107f48689e2da5.

2025-05-29 03:29 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Put strong::item:: at strong::index:: starting from 0, specified as an integer or float, or even array of float, replacing what is there.
Thanks! I searched the text `array of float` and could not find anything. 

Done in https://github.com/supercollider/supercollider/pull/6536/commits/b851561fdd38e8719f856ef62b107f48689e2da5.

2025-05-29 12:29 UTC, mtmccrea commented on HelpSource/Classes/ArrayedCollection.schelp
> +Out of range indices (≤ -1 or ≥ size) return code::nil:::
Thanks for the updates! I tried breaking this whole method description up, with some clarifications and formatting:
```
method::at
Returns the item at code::index::, specified as an integer (or float) starting from code::0::.

code::
x = [1, 2, 3];
x.at(2); // returns 3
x[2];    // equivalent shorthand syntax
::

The code::index:: can also be an link::Classes/Array:: of indices to extract specified elements:
code::
x = [10, 20, 30];

x.at([-1, 0, 1, 2, 3]); // returns [nil, 10, 20, 30, nil]
x.at((-1..3));          // same, as a range
x[(-1..3)];             // same as above

y = [0, 0, 2, 2, 1];
x[y];                   // returns [10, 10, 30, 30, 20]
::

Float indices are also supported with the following behavior:
list::
	## Positive float indices are floored to the nearest lower integer.
	## Negative float indices in the range (-1, 0) return the first item, code::this.at(0)::.
	## Out-of-range indices, code::<= -1:: or code::>= this.size::, return code::nil::.
::

code::
x = [10, 20];

x.at(-1);   // returns nil
x.at(-0.9); // returns 10
x.at(-0.1); // returns 10
x.at(-0);   // returns 10
x.at(0);    // returns 10
x.at(1.1);  // returns 20
x.at(1.9);  // returns 20
x.at(2);    // returns nil
::

A sound example:
code::
(
var pitches =  [43.0, 55.0, 58.86, 57.42, 67.0];
fork {
	pitches.size.do{ |i|
		{
			var freq = pitches[i].midicps;
			var env = Env.perc.ar(Done.freeSelf);
			SinOsc.ar(freq) * 0.1 * env
		}.play;
		0.2.wait
	}
}
)
::
```
What do you think? (btw, i didn't render this)

2025-05-29 12:29 UTC, mtmccrea commented on HelpSource/Classes/List.schelp
> +
This renders awkwardly. I think it's find to just have this text in the `note::` without the `defiinitionlist::`

That way also the repetition of "Size Limitations of Arrays and Flexibility of Lists in SuperCollider" can be removed.

As per style recommendations, you can instead use sentence case:
"Size limitations of arrays and flexibility of lists in SuperCollider"

2025-05-29 12:29 UTC, mtmccrea commented on HelpSource/Classes/ArrayedCollection.schelp
> +link::Classes/ArrayedCollection:: is an abstract class, a subclass of link::Classes/SequenceableCollection:: whose items are held in a vector of slots, indexable by a link::Classes/SimpleNumber:: sta
You don't need to `link::` to the class of the current help file, you can just used `code::ArrayedCollection::`, or `teletype::`

2025-05-30 10:07 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +link::Classes/ArrayedCollection:: is an abstract class, a subclass of link::Classes/SequenceableCollection:: whose items are held in a vector of slots, indexable by a link::Classes/SimpleNumber:: sta
Previously, I used 'code::ClassName::' or 'teletype::ClassName::' in this case (the class name is the name of the current help file).

However, a reviewer pointed this out to me once. Since then, I have always used 'link::Classes/classname::'.
I agree with your opinion, but what is the official way to do it?

2025-05-30 11:42 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +link::Classes/ArrayedCollection:: is an abstract class, a subclass of link::Classes/SequenceableCollection:: whose items are held in a vector of slots, indexable by a link::Classes/SimpleNumber:: sta
I left it as it is, I think there is no reason to use `link::Classes/ClassName:: when the the class name is the name of the current help file. 

However, I will follow the standard.

I could not edit [the document @mtmccrea  mentioned](https://github.com/supercollider/supercollider/wiki/Style-Guidelines%3A-SCDocs).

2025-05-30 13:03 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Out of range indices (≤ -1 or ≥ size) return code::nil:::
I think this is good, it's easy on the eye and reads well:
![Screenshot 2025-05-30 at 22 01 04](https://github.com/user-attachments/assets/e9a2efb6-398e-4883-8a88-19775e83b27b)

2025-05-30 13:11 UTC, prko commented on HelpSource/Classes/List.schelp
> +
Like as follows (I used `strong::` for `Index starting from 0`)?
![Screenshot 2025-05-30 at 22 09 44](https://github.com/user-attachments/assets/33449d02-7a85-4f38-909f-29fbb9643b1d)

2025-05-30 13:18 UTC, prko commented on HelpSource/Classes/ArrayedCollection.schelp
> +Out of range indices (≤ -1 or ≥ size) return code::nil:::
Thanks!
As there is only one day until the deadline, I have done this on https://github.com/supercollider/supercollider/pull/6536/commits/ad1e6097e0b717a246fc9d8e64d0fe03d8edcb72.

Please let me know if you think I should change anything!

2025-05-30 13:46 UTC, mtmccrea commented on HelpSource/Classes/List.schelp
> +
I think 
"Example:
... followed by the block code
"
Can be removed.

Then the second section of your note "Arrays and Lists use 0-based indexing...." can just keep that first sentence, then link to the `-at` method, where all that other information is described (we already did all that formatting and removing unnecessary text).

Otherwise the rest looks good, thanks!

2025-05-30 17:27 UTC, prko commented on HelpSource/Classes/List.schelp
> +
Thanks for your feedback! I appreciate the effort to streamline the documentation, but I want to ensure clarity for beginners as well.

>Then the second section of your note "Arrays and Lists use 0-based indexing...." can just keep that first sentence, then link to the -at method, where all that other information is described (we already did all that formatting and removing unnecessary text).

Could you take a close look at the complete `List.schelp` file? The part `strong::Index starting from 0::` is immediately followed by `anchor::Index starting from 0::`, and throughout the document, `See link::#Index starting from 0::.` appears seven times. Would it be beneficial to consolidate or adjust these references for better readability? 
**I used `anchor::` to minimise redundancy, as many users tend to access help documents through search results rather than reading them sequentially. Also, I think these parts help beginners to understand these things...**


>I think
"Example:
... followed by the block code
"
Can be removed.

Additionally, regarding this..., from what I understand, the revised version would look something like this:
![Screenshot 2025-05-30 at 23 14 25](https://github.com/user-attachments/assets/7725d8d5-071c-4548-aa1e-f5df1d7a3672)

```
note::
Size limitations of arrays and flexibility of lists in SuperCollider

Arrays have a fixed maximum size. If you add beyond that size, a new link::Classes/Array:: is created and returned, but you must use an assignment statement or the new array will be lost. (See the link::Classes/Array#description#Description:: section in link::Classes/Array::. documentation). The idiomatic way to add new item in link::Classes/Array:: is:

code::
x = x.add(i);
::


List has no size limitation and is thus more flexible, but has slightly more overhead.

anchor::Index starting from 0::

Arrays and Lists use 0-based indexing, meaning the first item is accessed with index 0.
::

Many of List's methods are inherited from link::Classes/SequenceableCollection:: or link::Classes/Collection:: and are documented in those helpfiles.
```

My intention with this PR is to ensure accessibility for beginners. The revised version, according to your last suggestion, will appear to be more compact than the help file in SC3.13:
![Screenshot 2025-05-30 at 23 11 55](https://github.com/user-attachments/assets/13bc15a3-896c-418b-be33-ac465e349aa4)

Do you think the more concise version, based on your suggestions, improves clarity for beginners? I’d love to refine it further while balancing both perspectives.

Thanks again for your insights! I look forward to your thoughts.

**Also, please feel free to directly point out if my PR is too wordy or repetitive, and whether that negatively impacts beginners.**

2025-05-31 15:47 UTC, telephon requested changes
I gave a few suggestions. I am slightly worried that we have to mention zero-based indexing now everywhere whenever an index is passed to a method ... But I suppose this will be enough and it is good that the methods that accept only ints are mentioned explicitly.

2025-05-31 15:47 UTC, telephon commented on HelpSource/Classes/List.schelp
> +Arrays have a fixed maximum size. If you add beyond that size, a new link::Classes/Array:: is created and returned, but you must use an assignment statement or the new array will be lost. (See the li
The text would read better like this (adjust to the formatting decision):

Arrays have a fixed maximum size. Adding beyond that size, a new link::Classes/Array:: is created and returned. In order to be able to use it, the variable holding the old array can be reassigned to the new one. Threfore, the idiomatic way to add new item in link::Classes/Array:: is:

2025-05-31 15:47 UTC, telephon commented on HelpSource/Classes/List.schelp
>  (
Since we want to make the examples accessible, it is better to emphasise the readability of the code:

```supercollider
(
x = Array.new(3); y = nil;
"Make an empty array of size 3: \nx:% \ny: %".format(x, y).postln;

5.do { |i| y = x.add(i) };

"After adding 5 items to each: \nx:%\ny: %".format(x, y).postln;
"Accessing:\nx.at(4): \nx:%\ny: %".format(x.at(4), y[4]).postln;"";
)
```

2025-05-31 16:15 UTC, mtmccrea commented
> I am slightly worried that we have to mention zero-based indexing now everywhere whenever an index is passed to a method ...

Thanks for bringing this up, I was circling around this as well, and ultimately my personal feeling is that this is such a basic principle that beginners are likely to come across it on their first day with SC, and then never need to see it again. I wonder if there's another solution. For example, if we link the word "index" to a glossary entry that describes what zero-based indexing is (anchors would have to be added to the definitionlist in the glossary page). Thoughts?

I think it's ok to still mention it in descriptions occasionally, perhaps in just the most basic methods like `at`, `put`, `insert`, `xxxAt`, `xxxPut`.

2025-05-31 16:25 UTC, HotwheelsSisyphus commented
Didn't someone above already bring up the idea of a general guide to indexing in sc?  
That could cover basics like 0-based indexing but also questions like "How do I do [thing from python/numpy/matlab/whatever] in sc", and mention not just .at but also wrapAt, etc. And it could be linked in the docs for the relevant collection classes.

2025-05-31 16:30 UTC, mtmccrea commented
> Didn't someone above already bring up the idea of a general guide to indexing in sc?

Yes, Julian suggested a tutorial on indexing. The alternative I'm suggesting is a glossary entry to be linked to. The most simple approach is just mention it at the head of the Help file and that could be enough.

2025-06-03 00:56 UTC, prko commented
Thank you for considering utilising the Glossary!

Before the introduction of the find feature in software, users needed to carefully read an entire text to fully understand context and find the necessary information. Now, with the find feature, it is often possible to jump directly to specific methods or terms—such as when consulting SuperCollider documentation for a particular method—without reading the whole document. Because of this, it becomes even more important to clearly state foundational information such as the fact that indices start at 0. There are a few ways to do this:  
- adding that information everywhere (which is not preferred, as it makes maintenance difficult),  
- including it in the Glossary or in the SequenceableCollection class documentation, and referring to it using `link::...::`.

Adding this to the Glossary is one potential approach. However, it's worth checking whether the keyword `index` fits well with the style and content of the current Glossary entries. For example:

```supercollider
## index
keyword:: index
|| In SuperCollider, an strong::index:: is a number used to access items in the subclasses of link::Classes/SequenceableCollection:: such as arrays and lists. Indexing starts at code::0::, so the first element of a collection is at index code::0::, the second at index code::1::, and so on. The item at a specific index is accessed using code::.at(index):: method or its shortcut code::[index]::. For example, in code::x = [10, 11, 12]::, code::x.at(1):: (or its shortcut code::x[1]::) returns `11`. If using an index that is outside the bounds of the collection (too low or too high), SuperCollider returns code::nil::.

strong::Example:::

code::
a = [100, 200, 300];
a.at(0); // Returns 100 (first item)
a[2]; // Returns 300 (third item)
a[5]; // Returns nil (index is out of bounds)
::
```
However, this example and detailed explanation may be too lengthy for the Glossary, and most Glossary items do not include code examples. A more concise entry might be:

```supercollider
## index
keyword:: index
|| In SuperCollider, an strong::index:: is a number used to access items in the subclasses of link::Classes/SequenceableCollection:: such as arrays and lists. Indexing starts at code::0::, so the first element of a collection is at index code::0::.
```

From this perspective, a shorter entry seems more appropriate for the Glossary’s style. However, I am still unsure whether `index` should be included as a Glossary item at all, or whether a fuller explanation (and example) would fit better in the documentation for SequenceableCollection. In my view, SequenceableCollection would be the best place for this, though I acknowledge this could be a personal bias.

---

Additionally, while [the current Glossary](http://doc.sccode.org/Guides/Glossary.html) is quite informative, it can be challenging for beginners, as many terms assume some programming background. The overall documentation would benefit from having simpler, context-driven explanations placed elsewhere, allowing the Glossary to function as a concise reference, while beginners could find more accessible explanations in other sections.

2025-06-03 01:21 UTC, prko commented on HelpSource/Classes/List.schelp
> +
See https://github.com/supercollider/supercollider/pull/6536/commits/87bea3eeaeb0ab3b12fec0958b35647a1249ff34!

I reconstructed this part using SequenceableCollection.

You wanted to delete the code example, but @telephon suggested revising it. It's hard to reach a compromise. For now, I have used @telephon's code. Please leave your opinions on the new commit. Thanks!

2025-06-03 01:23 UTC, prko commented on HelpSource/Classes/List.schelp
> +Arrays have a fixed maximum size. If you add beyond that size, a new link::Classes/Array:: is created and returned, but you must use an assignment statement or the new array will be lost. (See the li
Thanks, done in https://github.com/supercollider/supercollider/pull/6536/commits/87bea3eeaeb0ab3b12fec0958b35647a1249ff34!

2025-06-03 01:24 UTC, prko commented on HelpSource/Classes/List.schelp
>  (
Thanks. done in
https://github.com/supercollider/supercollider/pull/6536/commits/87bea3eeaeb0ab3b12fec0958b35647a1249ff34!

@mtmccrea:
I added comments in the code example. Please leave further comments on the new commit! Thanks!

2025-06-03 01:30 UTC, prko commented
I uploaded the commit https://github.com/supercollider/supercollider/pull/6536/commits/87bea3eeaeb0ab3b12fec0958b35647a1249ff34 to see how my suggestion looks. 

`Description` can have `subsection::`, so I used `subsection::` for `Size limitations of arrays and flexibility of lists in SuperCollider` and `Index. The rendered documentation screens are as follows:
![Screenshot 2025-06-03 at 10 26 54](https://github.com/user-attachments/assets/fa0aba5e-4ebc-4250-9cb1-545a109f2eb8)
![Screenshot 2025-06-03 at 10 27 06](https://github.com/user-attachments/assets/3f28f8b4-37b0-4b89-ae75-6cd7b739936a)

2025-06-03 08:30 UTC, mtmccrea commented
I think your solution of having subsections which can be linked to is a reasonable one.  I'll make a couple of comments in the revision.

Thanks for your attention detail with this!

2025-06-03 08:31 UTC, mtmccrea commented on HelpSource/Classes/SequenceableCollection.schelp
> +subsection::Index
Perhaps this subsection could be called "Indexing"

2025-06-03 08:31 UTC, mtmccrea commented on HelpSource/Classes/SequenceableCollection.schelp
> +
the sentence:

"For example, in code::x = [10, 11, 12]::, code::x.at(1):: (or its shortcut code::x[1]::) returns `11`."

can be removed because this paragraph is followed by examples.

2025-06-03 08:37 UTC, mtmccrea commented on HelpSource/Classes/List.schelp
> +::
suggestion for brevity (and clarification... List doesn't have a maxSize arg):
code::
(
// Create a new empty List with size: 3
x = List.new(3);

x.postln; // -> List[  ]

// Add numbers 0 to 4 to the List
5.do({ |i| x.add(i) });

// The list object has been modified in place with each added item
x.postln; // -> List[ 0, 1, 2, 3, 4 ]
)
::

2025-06-03 09:05 UTC, mtmccrea commented on HelpSource/Classes/List.schelp
> +// x.at(4) returns nil (out of bounds), y[4] returns the value (4).
This example is misleading because it's not properly growing `y`. It happens to work because you iterate 5 times, but change this to 10, and you'll get a result that would be confusing (y becomes `y: [ 0, 1, 2, 3, 9 ]`)

I still think this the postln statements are visually distracting and that information could be communicated with comments. And this is glossing over the potentially confusing behavior that `Array:-add` will grow `x` beyond `maxSize`, but only up to an internally preallocated size.

Something like this captures the behavior of all 3 cases:
```
// Create a new empty collections with maxSize 3:
x = Array.new(3); 
y = Array.new(3); 
z = List.new(3);

// Try to add 7 items to the array and list.
// If the array exceeds maxSize, it will only
// grow to an internally specified max size
( 
7.do { |i|
	x.add(i);
	y = y.add(i); // reassign array y on each add
	z.add(i);
};
)

// Attempt to access the 5th item:
x.at(4); // -> nil (out of bounds)
y.at(4); // -> 4
z.at(4); // -> 4

// x grew only to size 4
x.postln; // -> [ 0, 1, 2, 3 ]
y.postln; // -> [ 0, 1, 2, 3, 4, 5, 6 ]
z.postln; // -> List[ 0, 1, 2, 3, 4, 5, 6 ]
```

2025-06-03 11:56 UTC, prko commented on HelpSource/Classes/SequenceableCollection.schelp
> +subsection::Index
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/027b55d840163edc880635a823f21bb4652aa5ab.

2025-06-03 11:56 UTC, prko commented on HelpSource/Classes/SequenceableCollection.schelp
> +
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/027b55d840163edc880635a823f21bb4652aa5ab.

2025-06-03 11:57 UTC, prko commented on HelpSource/Classes/List.schelp
> +::
>List doesn't have a maxSize arg

Of course! Sorry!

Done in https://github.com/supercollider/supercollider/pull/6536/commits/027b55d840163edc880635a823f21bb4652aa5ab.

Thanks!

2025-06-03 11:57 UTC, prko commented on HelpSource/Classes/List.schelp
> +// x.at(4) returns nil (out of bounds), y[4] returns the value (4).
Thanks! Done in https://github.com/supercollider/supercollider/pull/6536/commits/027b55d840163edc880635a823f21bb4652aa5ab.

2025-06-03 12:10 UTC, mtmccrea commented on HelpSource/Classes/List.schelp
> +See link::Classes/SequenceableCollection#Index::.
These links will need to be updated to the new subsection title "Indexing"

2025-06-03 13:42 UTC, prko commented on HelpSource/Classes/List.schelp
> +See link::Classes/SequenceableCollection#Index::.
Thanks! It's done in https://github.com/supercollider/supercollider/pull/6536/commits/3335b22efa14de2a4a2c554c6a059f700d5f9a25.

I simply forgot.

2025-06-03 17:50 UTC, dyfer commented
@prko FYI this PR has conflicts with the develop branch now.

2025-06-03 23:37 UTC, prko commented
@dyfer 
Thanks, done!

2025-06-04 08:13 UTC, mtmccrea approved these changes
Approving this just to say it looks good to me and the numerous comments have been responded to (thanks @prko!).

But I want to leave the floor open to others who may want to continue their discussion about a guide/tutorial (either in this or a separate PR?)...

2025-06-04 16:04 UTC, dyfer commented
@telephon the PR is marked as "requested change" from you, have your comments been addressed?

2025-06-05 07:54 UTC, telephon commented
I don't know, acutally. There seems to be no simple way to find these requests. I'll just approve in order not to hold up things.

2025-06-05 07:54 UTC, telephon approved these changes

2025-06-05 14:27 UTC, dyfer commented
@HotwheelsSisyphus @tedmoore is it okay to merge this?

2025-06-05 15:52 UTC, tedmoore approved these changes

2025-06-05 15:57 UTC, merged